/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessPassSol from "./AccessPass.sol";
export type { accessPassSol };
export type { IURISwitchable } from "./IURISwitchable";
export type { URISwitchable } from "./URISwitchable";
