/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as accessPassSol from "./AccessPass.sol";
export { IURISwitchable__factory } from "./IURISwitchable__factory";
export { URISwitchable__factory } from "./URISwitchable__factory";
